package bcc

type InstanceModel struct {
	Id                     *string            `json:"id,omitempty"`
	SourceProductId        *string            `json:"sourceProductId,omitempty"`
	SourceProductType      *string            `json:"sourceProductType,omitempty"`
	SerialNumber           *string            `json:"serialNumber,omitempty"`
	KeypairId              *string            `json:"keypairId,omitempty"`
	KeypairName            *string            `json:"keypairName,omitempty"`
	Name                   *string            `json:"name,omitempty"`
	RoleName               *string            `json:"roleName,omitempty"`
	Hostname               *string            `json:"hostname,omitempty"`
	InstanceType           *string            `json:"instanceType,omitempty"`
	Spec                   *string            `json:"spec,omitempty"`
	EnableJumboFrame       *bool              `json:"enableJumboFrame,omitempty"`
	Status                 *string            `json:"status,omitempty"`
	Desc                   *string            `json:"desc,omitempty"`
	CreatedFrom            *string            `json:"createdFrom,omitempty"`
	PaymentTiming          *string            `json:"paymentTiming,omitempty"`
	ChargeStatus           *string            `json:"chargeStatus,omitempty"`
	DisplayChargeStatus    *string            `json:"displayChargeStatus,omitempty"`
	CreateTime             *string            `json:"createTime,omitempty"`
	ExpireTime             *string            `json:"expireTime,omitempty"`
	ReleaseTime            *string            `json:"releaseTime,omitempty"`
	InternalIp             *string            `json:"internalIp,omitempty"`
	PublicIp               *string            `json:"publicIp,omitempty"`
	CpuCount               *int32             `json:"cpuCount,omitempty"`
	RdmaUnitID             *string            `json:"rdmaUnitID,omitempty"`
	RdmaPodName            *string            `json:"rdmaPodName,omitempty"`
	DeletionProtection     *int32             `json:"deletionProtection,omitempty"`
	RdmaNicTopo            []*RdmaNicTopo     `json:"rdmaNicTopo,omitempty"`
	DeploysetList          []*DeploySetModel  `json:"deploysetList,omitempty"`
	ResGroupInfos          []*GroupInfo       `json:"resGroupInfos,omitempty"`
	HosteyeType            *string            `json:"hosteyeType,omitempty"`
	GpuCard                *string            `json:"gpuCard,omitempty"`
	GpuVideoMemory         *string            `json:"gpuVideoMemory,omitempty"`
	FpgaCard               *string            `json:"fpgaCard,omitempty"`
	CardCount              *string            `json:"cardCount,omitempty"`
	IsomerismCard          *string            `json:"isomerismCard,omitempty"`
	NpuVideoMemory         *string            `json:"npuVideoMemory,omitempty"`
	MemoryCapacityInGB     *int32             `json:"memoryCapacityInGB,omitempty"`
	LocalDiskSizeInGB      *int32             `json:"localDiskSizeInGB,omitempty"`
	ImageId                *string            `json:"imageId,omitempty"`
	ImageType              *string            `json:"imageType,omitempty"`
	ImageName              *string            `json:"imageName,omitempty"`
	OsVersion              *string            `json:"osVersion,omitempty"`
	OsArch                 *string            `json:"osArch,omitempty"`
	OsName                 *string            `json:"osName,omitempty"`
	PlacementPolicy        *string            `json:"placementPolicy,omitempty"`
	SubnetId               *string            `json:"subnetId,omitempty"`
	VpcId                  *string            `json:"vpcId,omitempty"`
	IsEipAutoRelatedDelete *bool              `json:"isEipAutoRelatedDelete,omitempty"`
	EhcClusterId           *string            `json:"ehcClusterId,omitempty"`
	DeploysetId            *string            `json:"deploysetId,omitempty"`
	ZoneName               *string            `json:"zoneName,omitempty"`
	FlavorSubType          *string            `json:"flavorSubType,omitempty"`
	ProductCategory        *string            `json:"productCategory,omitempty"`
	RepairStatus           *string            `json:"repairStatus,omitempty"`
	HostId                 *string            `json:"hostId,omitempty"`
	SwitchId               *string            `json:"switchId,omitempty"`
	RackId                 *string            `json:"rackId,omitempty"`
	DedicatedHostId        *string            `json:"dedicatedHostId,omitempty"`
	AutoRenew              *bool              `json:"autoRenew,omitempty"`
	AutoRenewPeriodUnit    *string            `json:"autoRenewPeriodUnit,omitempty"`
	AutoRenewPeriod        *int32             `json:"autoRenewPeriod,omitempty"`
	Ipv6                   *string            `json:"ipv6,omitempty"`
	NetEthQueueCount       *string            `json:"netEthQueueCount,omitempty"`
	EniQuota               *int32             `json:"eniQuota,omitempty"`
	EriQuota               *int32             `json:"eriQuota,omitempty"`
	RdmaType               *string            `json:"rdmaType,omitempty"`
	ServiceComponents      *map[string]string `json:"serviceComponents,omitempty"`
	Ipv6Addresses          []*string          `json:"ipv6Addresses,omitempty"`
	NicInfo                *NicInfo           `json:"nicInfo,omitempty"`
	EniNum                 *string            `json:"eniNum,omitempty"`
	Tags                   []*Tag             `json:"tags,omitempty"`
	Volumes                []*VolumeModel     `json:"volumes,omitempty"`
	NetworkCapacityInMbps  *int32             `json:"networkCapacityInMbps,omitempty"`
}
