package bcc

type CreateInstanceBySpecRequest struct {
	KeepImageLogin             *bool              `json:"keepImageLogin,omitempty"`
	BccCreateWithScript        *string            `json:"bccCreateWithScript,omitempty"`
	Name                       *string            `json:"name,omitempty"`
	CpuThreadConfig            *string            `json:"cpuThreadConfig,omitempty"`
	NumaConfig                 *string            `json:"numaConfig,omitempty"`
	EnableDeleteProtection     *bool              `json:"enableDeleteProtection,omitempty"`
	Hostname                   *string            `json:"hostname,omitempty"`
	AutoSeqSuffix              *bool              `json:"autoSeqSuffix,omitempty"`
	IsOpenHostnameDomain       *bool              `json:"isOpenHostnameDomain,omitempty"`
	AdminPass                  *string            `json:"adminPass,omitempty"`
	KeypairId                  *string            `json:"keypairId,omitempty"`
	AspId                      *string            `json:"aspId,omitempty"`
	SpecId                     *string            `json:"specId,omitempty"`
	EnableJumboFrame           *bool              `json:"enableJumboFrame,omitempty"`
	UserData                   *string            `json:"userData,omitempty"`
	DeletionProtection         *string            `json:"deletionProtection,omitempty"`
	AutoRenewTimeUnit          *string            `json:"autoRenewTimeUnit,omitempty"`
	AutoRenewTime              *int32             `json:"autoRenewTime,omitempty"`
	HosteyeType                *string            `json:"hosteyeType,omitempty"`
	EnableNuma                 *bool              `json:"enableNuma,omitempty"`
	DataPartitionType          *string            `json:"dataPartitionType,omitempty"`
	RootPartitionType          *string            `json:"rootPartitionType,omitempty"`
	CdsAutoRenew               *bool              `json:"cdsAutoRenew,omitempty"`
	CreateCdsList              []*CreateCdsModel  `json:"createCdsList,omitempty"`
	ImageId                    *string            `json:"imageId,omitempty"`
	Spec                       *string            `json:"spec,omitempty"`
	RoleName                   *string            `json:"roleName,omitempty"`
	BidModel                   *string            `json:"bidModel,omitempty"`
	BidPrice                   *string            `json:"bidPrice,omitempty"`
	RootDiskSizeInGb           *int32             `json:"rootDiskSizeInGb,omitempty"`
	RootDiskExtraIo            *string            `json:"rootDiskExtraIo,omitempty"`
	RootDiskStorageType        *string            `json:"rootDiskStorageType,omitempty"`
	NetworkCapacityInMbps      *int32             `json:"networkCapacityInMbps,omitempty"`
	EhcClusterId               *string            `json:"ehcClusterId,omitempty"`
	PurchaseCount              *int32             `json:"purchaseCount,omitempty"`
	PurchaseMinCount           *int32             `json:"purchaseMinCount,omitempty"`
	DedicatedHostId            *string            `json:"dedicatedHostId,omitempty"`
	RelationTag                *bool              `json:"relationTag,omitempty"`
	Tags                       []*TagModel        `json:"tags,omitempty"`
	FileSystems                []*FileSystemModel `json:"fileSystems,omitempty"`
	EphemeralDisks             []*EphemeralDisk   `json:"ephemeralDisks,omitempty"`
	SecurityGroupId            *string            `json:"securityGroupId,omitempty"`
	EnterpriseSecurityGroupId  *string            `json:"enterpriseSecurityGroupId,omitempty"`
	SecurityGroupIds           []*string          `json:"securityGroupIds,omitempty"`
	EnterpriseSecurityGroupIds []*string          `json:"enterpriseSecurityGroupIds,omitempty"`
	SubnetId                   *string            `json:"subnetId,omitempty"`
	DeployId                   *string            `json:"deployId,omitempty"`
	DeployIdList               []*string          `json:"deployIdList,omitempty"`
	EniIds                     []*string          `json:"eniIds,omitempty"`
	DisableRootDiskSerial      *string            `json:"disableRootDiskSerial,omitempty"`
	ZoneName                   *string            `json:"zoneName,omitempty"`
	InternalIps                []*string          `json:"internalIps,omitempty"`
	ResGroupId                 *string            `json:"resGroupId,omitempty"`
	IsEipAutoRelatedDelete     *bool              `json:"isEipAutoRelatedDelete,omitempty"`
	NetworkPurchaseType        *string            `json:"networkPurchaseType,omitempty"`
	InstanceType               *string            `json:"instanceType,omitempty"`
	InternetChargeType         *string            `json:"internetChargeType,omitempty"`
	EipName                    *string            `json:"eipName,omitempty"`
	IsOpenHostEye              *bool              `json:"isOpenHostEye,omitempty"`
	EnableHt                   *bool              `json:"enableHt,omitempty"`
	Billing                    *Billing           `json:"billing,omitempty"`
	IsOpenIpv6                 *bool              `json:"isOpenIpv6,omitempty"`
}
