package image

import (
	"github.com/baidubce/baiducloud-go-sdk/bce"
)

const (
	DEFAULT_ENDPOINT = "image." + bce.DEFAULT_REGION + ".baidubce.com"

	CONSTANT_REST = "rest"

	CONSTANT_2_0 = "2.0"

	CONSTANT_IMAGE_PROCESS = "image-process"

	CONSTANT_V1 = "v1"

	CONSTANT_DEHAZE = "dehaze"

	CONSTANT_IMAGE_CLASSIFY = "image-classify"

	CONSTANT_REALTIME_SEARCH = "realtime_search"

	CONSTANT_MATERIEL = "materiel"

	CONSTANT_UPDATE = "update"

	CONSTANT_DELETE = "delete"

	CONSTANT_SAME_HQ = "same_hq"

	CONSTANT_SEGMENT = "segment"

	CONSTANT_V2 = "v2"

	CONSTANT_LOGO = "logo"

	CONSTANT_ADD = "add"

	CONSTANT_LANDMARK = "landmark"

	CONSTANT_IMAGE_UNDERSTANDING = "image-understanding"

	CONSTANT_REQUEST = "request"

	CONSTANT_SEARCH = "search"

	CONSTANT_CONTRAST_ENHANCE = "contrast_enhance"

	CONSTANT_SIMILAR = "similar"

	CONSTANT_RETOUCHING = "retouching"

	CONSTANT_CREATE_TASK = "create_task"

	CONSTANT_PRODUCT = "product"

	CONSTANT_IMAGESEARCH = "imagesearch"

	CONSTANT_PICTUREBOOK = "picturebook"

	CONSTANT_QUERY_TASK = "query_task"

	CONSTANT_DISH = "dish"

	CONSTANT_SELFIE_ANIME = "selfie_anime"

	CONSTANT_PLANT = "plant"

	CONSTANT_ANIMAL = "animal"

	CONSTANT_IMAGE_DEFINITION_ENHANCE = "image_definition_enhance"

	CONSTANT_COLOR_ENHANCE = "color_enhance"

	CONSTANT_COLOURIZE = "colourize"

	CONSTANT_STYLE_TRANS = "style_trans"

	CONSTANT_INPAINTING = "inpainting"

	CONSTANT_MULTI_OBJECT_DETECT = "multi_object_detect"

	CONSTANT_GET_RESULT = "get-result"

	CONSTANT_CAR = "car"

	CONSTANT_REMOVE_MOIRE = "remove_moire"

	CONSTANT_IMAGE_QUALITY_ENHANCE = "image_quality_enhance"

	CONSTANT_CLASSIFY = "classify"

	CONSTANT_INGREDIENT = "ingredient"

	CONSTANT_ADVANCED_GENERAL = "advanced_general"

	CONSTANT_OBJECT_DETECT = "object_detect"

	CONSTANT_DOC_REPAIR = "doc_repair"

	CONSTANT_VEHICLE_DETECT = "vehicle_detect"

	CONSTANT_STRETCH_RESTORE = "stretch_restore"
)

// Client of image service is a kind of BceClient, so derived from BceClient
type Client struct {
	*bce.BceClient
}

func NewClient(ak, sk, endPoint string) (*Client, error) {
	if len(endPoint) == 0 {
		endPoint = DEFAULT_ENDPOINT
	}
	client, err := bce.NewBceClientWithAkSk(ak, sk, endPoint)
	if err != nil {
		return nil, err
	}
	return &Client{client}, nil
}

func NewClientWithApiKey(apiKey, endPoint string) (*Client, error) {
	if len(endPoint) == 0 {
		endPoint = DEFAULT_ENDPOINT
	}
	client, err := bce.NewBceClientWithApiKey(apiKey, endPoint)
	if err != nil {
		return nil, err
	}
	return &Client{client}, nil
}

func NewClientWithAccessToken(apiKey, secretKey, endPoint string) (*Client, error) {
	if len(endPoint) == 0 {
		endPoint = DEFAULT_ENDPOINT
	}
	client, err := bce.NewBceClientWithAccessToken(apiKey, secretKey, endPoint)
	if err != nil {
		return nil, err
	}
	return &Client{client}, nil
}

func getAdvancedGeneralUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V2 + bce.URI_PREFIX + CONSTANT_ADVANCED_GENERAL
}
func getAiRetouchingCreateTaskUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_RETOUCHING + bce.URI_PREFIX + CONSTANT_CREATE_TASK
}
func getAiRetouchingQueryTaskUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_RETOUCHING + bce.URI_PREFIX + CONSTANT_QUERY_TASK
}
func getAnimalUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_ANIMAL
}
func getCarUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_CAR
}
func getColorEnhanceUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_COLOR_ENHANCE
}
func getColourizeUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_COLOURIZE
}
func getContrastEnhanceUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_CONTRAST_ENHANCE
}
func getDehazeUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_DEHAZE
}
func getDishUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V2 + bce.URI_PREFIX + CONSTANT_DISH
}
func getDocRepairUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_DOC_REPAIR
}
func getImageDefinitionEnhanceUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_IMAGE_DEFINITION_ENHANCE
}
func getImageQualityEnhanceUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_IMAGE_QUALITY_ENHANCE
}
func getImageUnderstandingGetResultUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_IMAGE_UNDERSTANDING + bce.URI_PREFIX + CONSTANT_GET_RESULT
}
func getImageUnderstandingRequestUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_IMAGE_UNDERSTANDING + bce.URI_PREFIX + CONSTANT_REQUEST
}
func getIngredientUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_CLASSIFY + bce.URI_PREFIX + CONSTANT_INGREDIENT
}
func getInpaintingUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_INPAINTING
}
func getLandmarkUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_LANDMARK
}
func getLogoUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V2 + bce.URI_PREFIX + CONSTANT_LOGO
}
func getLogoAddUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_LOGO + bce.URI_PREFIX + CONSTANT_ADD
}
func getLogoDeleteUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_LOGO + bce.URI_PREFIX + CONSTANT_DELETE
}
func getMaterielImageAddUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_MATERIEL + bce.URI_PREFIX + CONSTANT_ADD
}
func getMaterielImageDeleteUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_MATERIEL + bce.URI_PREFIX + CONSTANT_DELETE
}
func getMaterielImageSearchUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_MATERIEL + bce.URI_PREFIX + CONSTANT_SEARCH
}
func getMaterielImageUpdateUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_MATERIEL + bce.URI_PREFIX + CONSTANT_UPDATE
}
func getMultiObjectDetectUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_MULTI_OBJECT_DETECT
}
func getObjectDetectUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_OBJECT_DETECT
}
func getPicturebookImageAddUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGESEARCH + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_PICTUREBOOK + bce.URI_PREFIX + CONSTANT_ADD
}
func getPicturebookImageDeleteUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGESEARCH + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_PICTUREBOOK + bce.URI_PREFIX + CONSTANT_DELETE
}
func getPicturebookImageSearchUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGESEARCH + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_PICTUREBOOK + bce.URI_PREFIX + CONSTANT_SEARCH
}
func getPicturebookImageUpdateUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGESEARCH + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_PICTUREBOOK + bce.URI_PREFIX + CONSTANT_UPDATE
}
func getPlantUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_PLANT
}
func getProductImageAddUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_PRODUCT + bce.URI_PREFIX + CONSTANT_ADD
}
func getProductImageDeleteUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_PRODUCT + bce.URI_PREFIX + CONSTANT_DELETE
}
func getProductImageSearchUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_PRODUCT + bce.URI_PREFIX + CONSTANT_SEARCH
}
func getProductImageUpdateUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_PRODUCT + bce.URI_PREFIX + CONSTANT_UPDATE
}
func getRemoveMoireUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REMOVE_MOIRE
}
func getSameImageAddUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_SAME_HQ + bce.URI_PREFIX + CONSTANT_ADD
}
func getSameImageDeleteUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_SAME_HQ + bce.URI_PREFIX + CONSTANT_DELETE
}
func getSameImageSearchUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_SAME_HQ + bce.URI_PREFIX + CONSTANT_SEARCH
}
func getSameImageUpdateUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_SAME_HQ + bce.URI_PREFIX + CONSTANT_UPDATE
}
func getSegmentUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_SEGMENT
}
func getSelfieAnimeUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_SELFIE_ANIME
}
func getSimilarImageAddUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_SIMILAR + bce.URI_PREFIX + CONSTANT_ADD
}
func getSimilarImageDeleteUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_SIMILAR + bce.URI_PREFIX + CONSTANT_DELETE
}
func getSimilarImageSearchUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_SIMILAR + bce.URI_PREFIX + CONSTANT_SEARCH
}
func getSimilarImageUpdateUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_REALTIME_SEARCH + bce.URI_PREFIX + CONSTANT_SIMILAR + bce.URI_PREFIX + CONSTANT_UPDATE
}
func getStretchRestoreUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_STRETCH_RESTORE
}
func getStyleTransUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_PROCESS + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_STYLE_TRANS
}
func getVehicleDetectUri() string {
	return bce.URI_PREFIX + CONSTANT_REST + bce.URI_PREFIX + CONSTANT_2_0 + bce.URI_PREFIX + CONSTANT_IMAGE_CLASSIFY + bce.URI_PREFIX + CONSTANT_V1 + bce.URI_PREFIX + CONSTANT_VEHICLE_DETECT
}
