package image

type PartialHumanOptions struct {
	BodySmoothHighpass      *float64 `json:"body_smooth_highpass,omitempty"`
	EyeWidthRight           *float64 `json:"eye_width_right,omitempty"`
	SkinRed                 *float64 `json:"skin_red,omitempty"`
	NoseScale               *float64 `json:"nose_scale,omitempty"`
	MakeupEyelashId         *int32   `json:"makeup_eyelash_id,omitempty"`
	RemoveEyeStreaks        *float64 `json:"remove_eye_streaks,omitempty"`
	AiBodyFlowThin          *float64 `json:"ai_body_flow_thin,omitempty"`
	JawWidthLeft            *float64 `json:"jaw_width_left,omitempty"`
	CheekboneWidthLeft      *float64 `json:"cheekbone_width_left,omitempty"`
	FaceColorSame           *float64 `json:"face_color_same,omitempty"`
	FaceSmall               *float64 `json:"face_small,omitempty"`
	RemoveForeheadWrinkles  *float64 `json:"remove_forehead_wrinkles,omitempty"`
	EyeScaleSame            *bool    `json:"eye_scale_same,omitempty"`
	MakeupShadow            *float64 `json:"makeup_shadow,omitempty"`
	MakeupEyebrow           *float64 `json:"makeup_eyebrow,omitempty"`
	MakeupBlush             *float64 `json:"makeup_blush,omitempty"`
	MakeupLipstick          *float64 `json:"makeup_lipstick,omitempty"`
	LegThin                 *float64 `json:"leg_thin,omitempty"`
	RemoveDoubleChin        *float64 `json:"remove_double_chin,omitempty"`
	FaceSymmetry            *float64 `json:"face_symmetry,omitempty"`
	EyeHeight               *float64 `json:"eye_height,omitempty"`
	EyeWidth                *float64 `json:"eye_width,omitempty"`
	RemoveBurstHairBody     *float64 `json:"remove_burst_hair_body,omitempty"`
	FaceSmoothNew           *float64 `json:"face_smooth_new,omitempty"`
	RemoveBodyFlaw          *float64 `json:"remove_body_flaw,omitempty"`
	TeethWhiteAddBright     *float64 `json:"teeth_white_add_bright,omitempty"`
	NeckThin                *float64 `json:"neck_thin,omitempty"`
	HairlineHeight          *float64 `json:"hairline_height,omitempty"`
	RightEyebrowEnhance     *float64 `json:"right_eyebrow_enhance,omitempty"`
	RemoveFaceGlossy        *float64 `json:"remove_face_glossy,omitempty"`
	ClothesFlawRemove       *float64 `json:"clothes_flaw_remove,omitempty"`
	FillHairPart            *float64 `json:"fill_hair_part,omitempty"`
	MakeupEyeballId         *int32   `json:"makeup_eyeball_id,omitempty"`
	RemoveLipWrinkles       *float64 `json:"remove_lip_wrinkles,omitempty"`
	ShinyEye                *float64 `json:"shiny_eye,omitempty"`
	MakeupEyebrowId         *int32   `json:"makeup_eyebrow_id,omitempty"`
	NoseHeight              *float64 `json:"nose_height,omitempty"`
	LipPlumpUp              *float64 `json:"lip_plump_up,omitempty"`
	FaceThin                *float64 `json:"face_thin,omitempty"`
	HeadSmall               *float64 `json:"head_small,omitempty"`
	SkinPrefer              *float64 `json:"skin_prefer,omitempty"`
	RemoveWhiteHair         *float64 `json:"remove_white_hair,omitempty"`
	EyePosition             *float64 `json:"eye_position,omitempty"`
	FaceSmoothGray          *float64 `json:"face_smooth_gray,omitempty"`
	SkinWhite               *float64 `json:"skin_white,omitempty"`
	ForeheadHeight          *float64 `json:"forehead_height,omitempty"`
	EyeScale                *float64 `json:"eye_scale,omitempty"`
	EyebrowDistance         *float64 `json:"eyebrow_distance,omitempty"`
	EyeHeightLeft           *float64 `json:"eye_height_left,omitempty"`
	EyeWidthLeft            *float64 `json:"eye_width_left,omitempty"`
	RemoveDarkCircles       *float64 `json:"remove_dark_circles,omitempty"`
	MakeupFreckleId         *int32   `json:"makeup_freckle_id,omitempty"`
	JawWidth                *float64 `json:"jaw_width,omitempty"`
	CheekboneWidthRight     *float64 `json:"cheekbone_width_right,omitempty"`
	LeftEyebrowEnhance      *float64 `json:"left_eyebrow_enhance,omitempty"`
	BodySmoothFine          *float64 `json:"body_smooth_fine,omitempty"`
	BodyColorSame           *float64 `json:"body_color_same,omitempty"`
	RemoveGlassesReflection *float64 `json:"remove_glasses_reflection,omitempty"`
	MakeupHighlight         *float64 `json:"makeup_highlight,omitempty"`
	RemovePolymastia        *int32   `json:"remove_polymastia,omitempty"`
	EyeDistanceRight        *float64 `json:"eye_distance_right,omitempty"`
	MouthScale              *float64 `json:"mouth_scale,omitempty"`
	MouthPosition           *float64 `json:"mouth_position,omitempty"`
	ChinHeight              *float64 `json:"chin_height,omitempty"`
	EyeHeightRight          *float64 `json:"eye_height_right,omitempty"`
	MakeupFaceId            *int32   `json:"makeup_face_id,omitempty"`
	BodySmooth              *float64 `json:"body_smooth,omitempty"`
	SkinColor               *float64 `json:"skin_color,omitempty"`
	FaceV                   *float64 `json:"face_v,omitempty"`
	EyeAngleRight           *float64 `json:"eye_angle_right,omitempty"`
	LipPlumpDown            *float64 `json:"lip_plump_down,omitempty"`
	FaceWidth               *float64 `json:"face_width,omitempty"`
	EyePositionLeft         *float64 `json:"eye_position_left,omitempty"`
	EyePositionRight        *float64 `json:"eye_position_right,omitempty"`
	NeckLength              *float64 `json:"neck_length,omitempty"`
	FaceShadow              *float64 `json:"face_shadow,omitempty"`
	SkinBright              *float64 `json:"skin_bright,omitempty"`
	SkinColorId             *int32   `json:"skin_color_id,omitempty"`
	NoseBridge              *float64 `json:"nose_bridge,omitempty"`
	NoseTip                 *float64 `json:"nose_tip,omitempty"`
	LeftSwanNeck            *float64 `json:"left_swan_neck,omitempty"`
	FaceSmoothHighpass      *float64 `json:"face_smooth_highpass,omitempty"`
	EyeScaleRight           *float64 `json:"eye_scale_right,omitempty"`
	RemoveFaceFlaw          *float64 `json:"remove_face_flaw,omitempty"`
	MouthWidth              *float64 `json:"mouth_width,omitempty"`
	FaceSmoothLowpass       *float64 `json:"face_smooth_lowpass,omitempty"`
	RemoveBurstHair         *float64 `json:"remove_burst_hair,omitempty"`
	MakeupEyeShadowId       *int32   `json:"makeup_eye_shadow_id,omitempty"`
	BodySmoothLowpass       *float64 `json:"body_smooth_lowpass,omitempty"`
	EyeAngle                *float64 `json:"eye_angle,omitempty"`
	AiBodyThin              *float64 `json:"ai_body_thin,omitempty"`
	MakeupEyelash           *float64 `json:"makeup_eyelash,omitempty"`
	MakeupFace              *float64 `json:"makeup_face,omitempty"`
	NoseWing                *float64 `json:"nose_wing,omitempty"`
	TeethWhite              *float64 `json:"teeth_white,omitempty"`
	BodyThin                *float64 `json:"body_thin,omitempty"`
	SkinSharpen             *float64 `json:"skin_sharpen,omitempty"`
	EyeScaleLeft            *float64 `json:"eye_scale_left,omitempty"`
	RemoveNeckWrinkles      *float64 `json:"remove_neck_wrinkles,omitempty"`
	CalvariaHeight          *float64 `json:"calvaria_height,omitempty"`
	JawWidthRight           *float64 `json:"jaw_width_right,omitempty"`
	WaistThin               *float64 `json:"waist_thin,omitempty"`
	FaceHighlight           *float64 `json:"face_highlight,omitempty"`
	RemoveEyeAroundWrinkles *float64 `json:"remove_eye_around_wrinkles,omitempty"`
	EyebrowThickness        *float64 `json:"eyebrow_thickness,omitempty"`
	TeethRepair             *int32   `json:"teeth_repair,omitempty"`
	RightSwanNeck           *float64 `json:"right_swan_neck,omitempty"`
	ArmThin                 *float64 `json:"arm_thin,omitempty"`
	MakeupEyeball           *float64 `json:"makeup_eyeball,omitempty"`
	CheekboneWidth          *float64 `json:"cheekbone_width,omitempty"`
	EyeAngleLeft            *float64 `json:"eye_angle_left,omitempty"`
	EyeDistanceLeft         *float64 `json:"eye_distance_left,omitempty"`
	MakeupEyeShadow         *float64 `json:"makeup_eye_shadow,omitempty"`
	TeethWhiteDesYellow     *float64 `json:"teeth_white_des_yellow,omitempty"`
	FaceSmoothFine          *float64 `json:"face_smooth_fine,omitempty"`
	MakeupFreckle           *float64 `json:"makeup_freckle,omitempty"`
	MakeupBlushId           *int32   `json:"makeup_blush_id,omitempty"`
	RemoveLaughLine         *float64 `json:"remove_laugh_line,omitempty"`
	MakeupLipstickId        *int32   `json:"makeup_lipstick_id,omitempty"`
	FaceSmooth              *float64 `json:"face_smooth,omitempty"`
	EyebrowHeight           *float64 `json:"eyebrow_height,omitempty"`
	EyeDistance             *float64 `json:"eye_distance,omitempty"`
	RemoveFaceMoles         *int32   `json:"remove_face_moles,omitempty"`
	RemoveStretchMark       *float64 `json:"remove_stretch_mark,omitempty"`
	RemoveBurstHairBack     *float64 `json:"remove_burst_hair_back,omitempty"`
}
